version: '3.8'

services:
  db:
    image: postgres:13
    container_name: community_app_db
    environment:
      POSTGRES_USER: community_user
      POSTGRES_PASSWORD: community_password
      POSTGRES_DB: community_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - community_network

  backend:
    build: ./backend
    container_name: community_app_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://community_user:community_password@db:5432/community_db
    depends_on:
      - db
    networks:
      - community_network

  frontend:
    build: ./frontend
    container_name: community_app_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - community_network

volumes:
  postgres_data:

networks:
  community_network:
    driver: bridge
