[tool.black]
line-length = 100
target-version = ["py39"]

[tool.ruff]
line-length = 100
src = ["backend/app", "backend/tests"]
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["B008", "E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
